Repository aragon/client, pull requests merged in 2018-05, with the labels that each got.

#224 Add ability to set the ENS registry address and expected network type via env variables
  README.md
  src/apps/Settings/Settings.js
  src/environment.js
  src/local-settings.js
  src/network-config.js
  src/onboarding/Start.js
Labels: epic: 0.5.1 additions, sprint: 0.5.1

#230 Update @aragon/wrapper for ERC897 support
  package.json
Labels: enhancement, epic: 0.5.1 additions, sprint: 0.5.1

#237 Refactor app loading to correctly take into account start_url and relative asset locations
  package.json
  src/aragonjs-wrapper.js
  src/components/App/AppIFrame.js
  src/components/MenuPanel/MenuPanel.js
  src/utils.js
Labels: epic: 0.5.1 additions, sprint: 0.5.1

#241 Improvements to local configuration settings
  package.json
  scripts/dev-launch.sh
  src/local-settings.js
Labels: epic: dev tooling, sprint: 0.5.1
