Repository aragon/client, pull requests merged in 2018-06, with the labels that each got.

#269 Fix typo
  README.md
Labels: bug

#275 Fix travis and add build as a step in CI
  .travis.yml
Labels: epic: in sprint addition, sprint: 0.5.2

#277 Configure default ETH node using network
  package.json
  scripts/launch-local.sh
  scripts/launch-mainnet.sh
  src/environment.js
  src/local-settings.js
  src/network-config.js
Labels: epic: dev tooling, sprint: 0.5.2

#279 Fix settings
  package.json
  src/App.js
  src/Wrapper.js
  src/apps/Settings/DaoSettings.js
  src/apps/Settings/Settings.js
  src/components/Etherscan/EtherscanLink.js
  src/context/provideNetwork.js
  src/environment.js
  src/onboarding/Onboarding.js
  src/onboarding/Start.js
Labels: epic: in sprint addition, sprint: 0.5.2
